### ISSUE TITLE
[bug]: jqui - Input Time

### ISSUE THREAD

**Issue by PiemurIsBack** [ioBroker/ioBroker.vis-2#183]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

 jqui - Input Time (gestylt)

![image](https://github.com/ioBroker/ioBroker.vis-2/assets/116312454/e54f9302-165d-4467-b108-e4f5218dc59b)

Nach Eingabe einer Zeit wird im Datenpunkt "2023-11-20T01:10:00.000Z" dieses Format abgelegt.
(Datenpunkt ist als string mit unit hh:mm definiert)

Ist im Datenpunkt der Wert "2023-11-20T01:10:00.000Z" gespeichert, stürzt VIS-2 nach einem Reload des Fensters mit eine weissen Bildschirm ab. Setze ich den Datenpunkt manuell auf "06:45" kann ich die Seite wieder laden. 
Siehe F12-Protokoll vom Chrome-Browser

Aufgefallen ist mir dies nach der Installation von VIS-2 Version 2.6.1 (ich vermute aber, dass dies schon mit 2.5.4 vorhanden war)

Ich verwende das Widget für den Adapter HeatingControl über Pittini´s Simple-Projekt um die Zeiten einzustellen.
In der Vis-2  Version 2.4.x hatte dies funktioniert, wobei mir bei der Zeit-Eingabe ein anderes Design angezeigt wurde.
Daher vermute ich, dass eine alte Version vom Widget hinterlegt ist. "Warum" ist mir nicht bekannt.

### To Reproduce

Use Gestylt jqui - Input Time
Datapoint auswählen (String mit unit: "hh:mm" )
Zeit auswählen

### Expected behavior

Eigendlich kenn ich das Widget mit "Schiebe-Reglern" zur Einstellung der Zeit

Datenpunkt wird mit String mit unit: "hh:mm" gespeichert

### Screenshots & Logfiles

iobroker.vis-2@2.6.1 using theme "colored"
Prompt.js:14 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:15 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:16 Help us to create open source project with reactJS!
Prompt.js:17 See you :)
socket.io.js:66 [2023-11-20T17:10:10.038Z] Try to connect
instrument.ts:145 Version vis-colorpicker: 2.0.3
instrument.ts:145 Version vis-jqui-mfd: 1.0.12
instrument.ts:145 Metro version: "1.2.0"
instrument.ts:145 Version trashschedule: 2.3.0
instrument.ts:145 Version Info-Adapter-Widget: 1.9.26
instrument.ts:145 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
instrument.ts:145 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
instrument.ts:145 Version vis-materialdesign: 0.5.94
instrument.ts:145 vis-materialdesign: vibration supported by device: 'true'
instrument.ts:145 vis-materialdesign: click audio file '/vis.0/materialdesign-widgets-click-sound.mp3' not exists!
(anonym) @ instrument.ts:145
instrument.ts:145 sentry initialized for vis-materialdesign
instrument.ts:145 Version vis-material-advanced: 1.7.3
:8082/vis-2/widgets/vis-2-widgets-gauges/customWidgets.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
instrument.ts:145 Cannot load i18n "vis2gaugeWidgets": Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: {}
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: {}
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: Error: Cannot load vis2gaugeWidgets from ./widgets/vis-2-widgets-gauges/customWidgets.js
(anonym) @ instrument.ts:145
instrument.ts:145 Cannot load widget system.adapter.vis-2-widgets-gauges.0: {}
(anonym) @ instrument.ts:145
instrument.ts:145 Translate: jqui_Input Time
instrument.ts:145 Translate: jqui_icon_increment
instrument.ts:145 Translate: jqui_Input Date
instrument.ts:145 Translate: colorpicker
instrument.ts:145 Translate: dwd
instrument.ts:145 Translate: echarts
instrument.ts:145 Translate: hqwidgets
instrument.ts:145 Translate: info
instrument.ts:145 Translate: jqplot
instrument.ts:145 Translate: jqui-mfd
instrument.ts:145 Translate: materialdesign
instrument.ts:145 Translate: metro
instrument.ts:145 Translate: swipe
instrument.ts:145 Translate: timeandweather
instrument.ts:145 Translate: trashschedule
instrument.ts:145 Translate: vis-inventwo
instrument.ts:145 Translate: vis-material-advanced
instrument.ts:145 Recalculate fields
instrument.ts:145 Translate: show code
instrument.ts:145 Translate: standard
instrument.ts:145 Translate: outlined
instrument.ts:145 Translate: filled
instrument.ts:145 Translate: 2 minutes
instrument.ts:145 Translate: 3 minutes
instrument.ts:145 Translate: 4 minutes
instrument.ts:145 Translate: 15 minutes
instrument.ts:145 Translate: 20 minutes
instrument.ts:145 Translate: 60 minutes
instrument.ts:145 Common user CSS not found: Not exists
(anonym) @ instrument.ts:145
instrument.ts:145 TypeError: e.minute is not a function
    at D.getMinutes (AdapterDayjs.js:503:20)
    at n (validateTime.js:46:47)
    at o (useValidation.js:10:27)
    at h (usePickerValue.js:191:3)
    at M (usePicker.js:21:31)
    at F (useDesktopPicker.js:61:7)
    at DesktopTimePicker.js:83:7
    at Cr (react-dom.production.min.js:167:247)
    at Vs (react-dom.production.min.js:193:57)
    at Cl (react-dom.production.min.js:294:275)
    at Hi (react-dom.production.min.js:280:389)
    at gi (react-dom.production.min.js:280:320)
    at fi (react-dom.production.min.js:280:180)
    at ri (react-dom.production.min.js:271:88)
    at oi (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:145
react-dom.production.min.js:283 Uncaught TypeError: e.minute is not a function
    at D.getMinutes (AdapterDayjs.js:503:20)
    at n (validateTime.js:46:47)
    at o (useValidation.js:10:27)
    at h (usePickerValue.js:191:3)
    at M (usePicker.js:21:31)
    at F (useDesktopPicker.js:61:7)
    at DesktopTimePicker.js:83:7
    at Cr (react-dom.production.min.js:167:247)
    at Vs (react-dom.production.min.js:193:57)
    at Cl (react-dom.production.min.js:294:275)
    at Hi (react-dom.production.min.js:280:389)
    at gi (react-dom.production.min.js:280:320)
    at fi (react-dom.production.min.js:280:180)
    at ri (react-dom.production.min.js:271:88)
    at oi (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
instrument.ts:145 [waitForWidgets] stop waiting for vis widgets after 500 retries
(anonym) @ instrument.ts:145

### Adapter version

2.6.1

### js-controller version

5.0.16

### Node version

18.17.0 

### Operating system

Rapsberry Pi 4, bullseye

**Comment by smahom** [comment]
Hallo, 
ich habe den identischen Fehler (Bei allen Widgets: tplJquiInputDate) Sobald ein Status verlinkt ist wird der Error produziert. Das dürfte am React liegen, evtl. auch an der React Version. (Hatte das dazu gefunden: https://stackoverflow.com/questions/76035120/getting-typeerror-date-isbefore-is-not-a-function-while-using-material-ui-date) 
Leider kenne ich mich nicht gut genug aus um den Fehler selbst zu beheben.
Anbei ein paar Daten:
**Screenshots & Logfiles**
`iobroker.vis-2@2.9.12 using theme "colored"
App.jsx:80 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

App.jsx:80 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
App.jsx:80 Help us to create open source project with reactJS!
App.jsx:80 See you :)
socket.io.js:66 [2024-01-06T20:00:29.049Z] Try to connect
VM660:78 Version vis-colorpicker: 2.0.3
3visEngine.jsx:1503 Skip script "dwd" inline
visEngine.jsx:1503 Skip script "info" ../adapter/info/lib/js/commons.js
visEngine.jsx:1503 Skip script "info" ../adapter/info/lib/js/popupnews.js
visEngine.jsx:1503 Skip script "info" widgets/info/js/info.js
2visEngine.jsx:1503 Skip script "info" inline
3visEngine.jsx:1503 Skip script "swipe" inline
visEngine.jsx:1503 Skip script "tabs" inline
load script:41 
        
        
       GET https://192.168.10.15:8082/vis-2/widgets/vis-2-widgets-material/static/js/node_modules_react_jsx-runtime_js-_c9183.ab79e858.chunk.js net::ERR_ABORTED 404 (Not Found)
s.l @ load script:41
s.f.j @ jsonp chunk loading:43
(anonym) @ ensure chunk:6
s.e @ ensure chunk:5
./Vacuum @ container-entry:54
r @ container-entry:64
(anonym) @ visUtils.jsx:795
Promise.then (async)
(anonym) @ visUtils.jsx:795
(anonym) @ visUtils.jsx:814
u @ visUtils.jsx:812
(anonym) @ visUtils.jsx:945
Promise.then (async)
(anonym) @ visUtils.jsx:945
(anonym) @ visUtils.jsx:873
Promise.then (async)
g @ visUtils.jsx:849
(anonym) @ visWidgetsCatalog.jsx:111
n @ helpers.ts:98
setTimeout (async)
(anonym) @ trycatch.ts:108
(anonym) @ visWidgetsCatalog.jsx:110
collectRxInformation @ visWidgetsCatalog.jsx:109
onWidgetsLoaded @ App.jsx:802
onLoaded @ App.jsx:986
loadWidgets @ visEngine.jsx:1534
await in loadWidgets (async)
(anonym) @ visEngine.jsx:232
Promise.then (async)
qe @ visEngine.jsx:222
Wo @ react-dom.production.min.js:147
Ls @ react-dom.production.min.js:198
yi @ react-dom.production.min.js:292
Hl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
fl @ react-dom.production.min.js:280
ol @ react-dom.production.min.js:268
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
JQuiWriteState.jsx:180 Translate: Write state
JQuiButtonDialogClose.jsx:106 Translate: jqui_Close
JQuiInput.jsx:55 Translate: jqui_input
JQuiBinaryState.jsx:124 Translate: jqui_off
JQuiBinaryState.jsx:131 Translate: jqui_on
JQuiState.jsx:185 Translate: Value
visWidgetsCatalog.jsx:173 Ignored dwd/tplDwdAdapterSmall because not used in project
visWidgetsCatalog.jsx:173 Ignored dwd/tplDwdAdapter because not used in project
visWidgetsCatalog.jsx:173 Ignored info/tplInfoMessages because not used in project
visWidgetsCatalog.jsx:173 Ignored info/tplInfoCalendar because not used in project
visWidgetsCatalog.jsx:173 Ignored swipe/tplSwipe because not used in project
visWidgetsCatalog.jsx:173 Ignored swipe/tplCarousel because not used in project
visEngine.jsx:1959 Common user CSS not found: Not exists
(anonym) @ console.ts:40
(anonym) @ visEngine.jsx:1959
Promise.catch (async)
updateCommonCss @ visEngine.jsx:1959
render @ visEngine.jsx:2007
js @ react-dom.production.min.js:204
Ls @ react-dom.production.min.js:203
yi @ react-dom.production.min.js:292
Hl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
fl @ react-dom.production.min.js:280
ol @ react-dom.production.min.js:268
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
visEngine.jsx:1831 [2024-01-06T20:00:32.060Z] +SUBSCRIBE: 0_userdata.0.Zeitschaltuhren.Zentral_Zeitschaltuhr_Jahreszeit_Modus
visEngine.jsx:1831 [2024-01-06T20:00:32.083Z] +SUBSCRIBE: openknx.0.Zentral.Tag_Nacht_Jahreszeit.Sommer(1)_Winter(0)
visEngine.jsx:1831 [2024-01-06T20:00:32.089Z] +SUBSCRIBE: 0_userdata.0.Zeitschaltuhren.TEST_Zentral_Zeitschaltuhr_Beginn_Sommer
JQuiInput.jsx:186 Cannot get state : The id is empty! Please provide a valid id.
(anonym) @ console.ts:40
componentDidMount @ JQuiInput.jsx:186
await in componentDidMount (async)
xi @ react-dom.production.min.js:261
Hi @ react-dom.production.min.js:260
Mi @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Vl @ react-dom.production.min.js:281
ol @ react-dom.production.min.js:270
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
console.ts:40 TypeError: e.isBefore is not a function
    at b.isBeforeDay (AdapterDayjs.js:438:22)
    at T (validateDate.js:34:43)
    at o (useValidation.js:10:27)
    at h (usePickerValue.js:191:3)
    at M (usePicker.js:21:31)
    at D (useDesktopPicker.js:62:7)
    at DesktopDatePicker.js:61:7
    at yr (react-dom.production.min.js:167:247)
    at Vs (react-dom.production.min.js:193:57)
    at yi (react-dom.production.min.js:294:275)
    at Hl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at fl (react-dom.production.min.js:280:180)
    at rl (react-dom.production.min.js:271:88)
    at ol (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ console.ts:40
vs @ react-dom.production.min.js:189
c.callback @ react-dom.production.min.js:189
Po @ react-dom.production.min.js:144
xi @ react-dom.production.min.js:262
Hi @ react-dom.production.min.js:260
Mi @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
Vl @ react-dom.production.min.js:281
ol @ react-dom.production.min.js:270
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
react-dom.production.min.js:283 Uncaught TypeError: e.isBefore is not a function
    at b.isBeforeDay (AdapterDayjs.js:438:22)
    at T (validateDate.js:34:43)
    at o (useValidation.js:10:27)
    at h (usePickerValue.js:191:3)
    at M (usePicker.js:21:31)
    at D (useDesktopPicker.js:62:7)
    at DesktopDatePicker.js:61:7
    at yr (react-dom.production.min.js:167:247)
    at Vs (react-dom.production.min.js:193:57)
    at yi (react-dom.production.min.js:294:275)
    at Hl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at fl (react-dom.production.min.js:280:180)
    at rl (react-dom.production.min.js:271:88)
    at ol (react-dom.production.min.js:268:429)
    at V (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
isBeforeDay @ AdapterDayjs.js:438
T @ validateDate.js:34
o @ useValidation.js:10
h @ usePickerValue.js:191
M @ usePicker.js:21
D @ useDesktopPicker.js:62
(anonym) @ DesktopDatePicker.js:61
yr @ react-dom.production.min.js:167
Vs @ react-dom.production.min.js:193
yi @ react-dom.production.min.js:294
Hl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
fl @ react-dom.production.min.js:280
rl @ react-dom.production.min.js:271
ol @ react-dom.production.min.js:268
V @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14`

Vis-2 Adapter version
2.9.12

WEB-Adapter
6.2.3

Node version
18.17.1
